LIGHT_MODEL=["light"]
SWITCH_MODEL=["switch"]
MEDIA_PLAYER_MODEL=["tv",'stb']
FAN_MODEL=["fan"]
CLIMATE_MODEL = ['ac']



TYPE_HUMI_019="0001-0401-0001"
TYPE_HUMI_023="0001-0401-0002"


BRIGHTNESS_INCREASE_ACTION="light.brightness_increase"
BRIGHTNESS_INCREASE_KEYID=2202
BRIGHTNESS_DECREASE_ACTION="light.brightness_decrease"
BRIGHTNESS_DECREASE_KEYID=2207
COLOR_TEMPERATURE_ACTION="light.temperature"
COLOR_TEMPERATURE_KEYID=997
CLR_TEMP_INCREASE_ACTION="Clr.temp_increase"
CLR_TEMP_INCREASE_KEYID=6047
CLR_TEMP_DECREASE_ACTION="Clr.temp_decrease"
CLR_TEMP_DECREASE_KEYID=6052
