# Describes the format for available ifuturehome services

pull_devices:
  description: Pull device list from ifuturehome server.

force_update:
  description: Force all ifuturehome devices to pull data.
